# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrarCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroCliente(object):
    def setupUi(self, CadastroCliente):
        CadastroCliente.setObjectName("CadastroCliente")
        CadastroCliente.resize(1281, 720)
        self.centralwidget = QtWidgets.QWidget(CadastroCliente)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_topRectangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_topRectangle.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_topRectangle.setMaximumSize(QtCore.QSize(16777215, 116))
        self.frame_topRectangle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_topRectangle.setStyleSheet("background: #FFD580;\n"
"")
        self.frame_topRectangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_topRectangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_topRectangle.setLineWidth(1)
        self.frame_topRectangle.setObjectName("frame_topRectangle")
        self.verticalLayout.addWidget(self.frame_topRectangle)
        self.frame_whiteRectangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_whiteRectangle.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.frame_whiteRectangle.setFont(font)
        self.frame_whiteRectangle.setStyleSheet("background-color: #faf9f6;")
        self.frame_whiteRectangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_whiteRectangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_whiteRectangle.setObjectName("frame_whiteRectangle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_whiteRectangle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_whiteRectangle)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(1070, 460))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_loginBox = QtWidgets.QFrame(self.frame)
        self.frame_loginBox.setEnabled(True)
        self.frame_loginBox.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_loginBox.setMaximumSize(QtCore.QSize(1070, 320))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.frame_loginBox.setFont(font)
        self.frame_loginBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_loginBox.setStyleSheet("background: #FFD580;\n"
"border-radius: 20px;\n"
"font-size: 20px;")
        self.frame_loginBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_loginBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_loginBox.setObjectName("frame_loginBox")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user.setGeometry(QtCore.QRect(40, 70, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_user_2 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_2.setGeometry(QtCore.QRect(40, 150, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_2.setFont(font)
        self.lineEdit_user_2.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_2.setText("")
        self.lineEdit_user_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_2.setObjectName("lineEdit_user_2")
        self.lineEdit_user_3 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_3.setGeometry(QtCore.QRect(40, 230, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_3.setFont(font)
        self.lineEdit_user_3.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_3.setText("")
        self.lineEdit_user_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_3.setObjectName("lineEdit_user_3")
        self.lineEdit_user_4 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_4.setGeometry(QtCore.QRect(390, 150, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_4.setFont(font)
        self.lineEdit_user_4.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_4.setText("")
        self.lineEdit_user_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_4.setObjectName("lineEdit_user_4")
        self.lineEdit_user_5 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_5.setGeometry(QtCore.QRect(390, 70, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_5.setFont(font)
        self.lineEdit_user_5.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_5.setText("")
        self.lineEdit_user_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_5.setObjectName("lineEdit_user_5")
        self.lineEdit_user_6 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_6.setGeometry(QtCore.QRect(390, 230, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_6.setFont(font)
        self.lineEdit_user_6.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_6.setText("")
        self.lineEdit_user_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_6.setObjectName("lineEdit_user_6")
        self.lineEdit_user_7 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_7.setGeometry(QtCore.QRect(750, 150, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_7.setFont(font)
        self.lineEdit_user_7.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_7.setText("")
        self.lineEdit_user_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_7.setObjectName("lineEdit_user_7")
        self.lineEdit_user_8 = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user_8.setGeometry(QtCore.QRect(750, 70, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user_8.setFont(font)
        self.lineEdit_user_8.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user_8.setText("")
        self.lineEdit_user_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user_8.setObjectName("lineEdit_user_8")
        self.label = QtWidgets.QLabel(self.frame_loginBox)
        self.label.setGeometry(QtCore.QRect(40, 30, 151, 16))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.frame_loginBox)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(1070, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_enter = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_enter.setMaximumSize(QtCore.QSize(230, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_enter.setStyleSheet("QPushButton {\n"
"    background: #FFAA00;\n"
"    border-radius: 15px;\n"
"    font-size: 22px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #ed9e02;\n"
"}")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.horizontalLayout_2.addWidget(self.pushButton_enter)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_whiteRectangle)
        CadastroCliente.setCentralWidget(self.centralwidget)

        self.retranslateUi(CadastroCliente)
        QtCore.QMetaObject.connectSlotsByName(CadastroCliente)

    def retranslateUi(self, CadastroCliente):
        _translate = QtCore.QCoreApplication.translate
        CadastroCliente.setWindowTitle(_translate("CadastroCliente", "CadastroCliente"))
        self.lineEdit_user.setPlaceholderText(_translate("CadastroCliente", "Nome"))
        self.lineEdit_user_2.setPlaceholderText(_translate("CadastroCliente", "CPF"))
        self.lineEdit_user_3.setPlaceholderText(_translate("CadastroCliente", "Data de nascimento"))
        self.lineEdit_user_4.setPlaceholderText(_translate("CadastroCliente", "Cidade"))
        self.lineEdit_user_5.setPlaceholderText(_translate("CadastroCliente", "Endereço"))
        self.lineEdit_user_6.setPlaceholderText(_translate("CadastroCliente", "Estado"))
        self.lineEdit_user_7.setPlaceholderText(_translate("CadastroCliente", "E-Mail"))
        self.lineEdit_user_8.setPlaceholderText(_translate("CadastroCliente", "Telefone"))
        self.label.setText(_translate("CadastroCliente", "Dados Pessoais"))
        self.pushButton_enter.setText(_translate("CadastroCliente", "CADASTRAR"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastroCliente = QtWidgets.QMainWindow()
    ui = Ui_CadastroCliente()
    ui.setupUi(CadastroCliente)
    CadastroCliente.show()
    sys.exit(app.exec_())
