# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_topRectangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_topRectangle.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_topRectangle.setMaximumSize(QtCore.QSize(16777215, 116))
        self.frame_topRectangle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_topRectangle.setStyleSheet("background: #FFD580;\n"
"")
        self.frame_topRectangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_topRectangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_topRectangle.setLineWidth(1)
        self.frame_topRectangle.setObjectName("frame_topRectangle")
        self.verticalLayout.addWidget(self.frame_topRectangle)
        self.frame_whiteRectangle = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.frame_whiteRectangle.setFont(font)
        self.frame_whiteRectangle.setStyleSheet("background-color: #faf9f6")
        self.frame_whiteRectangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_whiteRectangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_whiteRectangle.setObjectName("frame_whiteRectangle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_whiteRectangle)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_loginBox = QtWidgets.QFrame(self.frame_whiteRectangle)
        self.frame_loginBox.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_loginBox.setMaximumSize(QtCore.QSize(400, 480))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.frame_loginBox.setFont(font)
        self.frame_loginBox.setStyleSheet("background-color: #e5e5e5;\n"
"border-radius: 20px;\n"
"font-size: 20px;")
        self.frame_loginBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_loginBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_loginBox.setObjectName("frame_loginBox")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_user.setGeometry(QtCore.QRect(40, 50, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 40px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_loginBox)
        self.lineEdit_password.setGeometry(QtCore.QRect(40, 150, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 15px;\n"
"    color: #C4C4C4;\n"
"    padding: 0px 0px 0px 40px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid #ffaa00;\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_enter = QtWidgets.QPushButton(self.frame_loginBox)
        self.pushButton_enter.setGeometry(QtCore.QRect(120, 250, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setStyleSheet("QPushButton {\n"
"    background: #FFAA00;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #ed9e02\n"
"}")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.pushButton_createAccount = QtWidgets.QPushButton(self.frame_loginBox)
        self.pushButton_createAccount.setGeometry(QtCore.QRect(120, 390, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_createAccount.setFont(font)
        self.pushButton_createAccount.setStyleSheet("QPushButton {\n"
"    background: #F5F5F5;\n"
"    border-radius: 15px;    \n"
"    border: 3px solid #FFAA00;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #efeeea;\n"
"    border: 3px solid #ed9e02;\n"
"}")
        self.pushButton_createAccount.setObjectName("pushButton_createAccount")
        self.frame_lineRight_2 = QtWidgets.QFrame(self.frame_loginBox)
        self.frame_lineRight_2.setGeometry(QtCore.QRect(0, 350, 135, 2))
        self.frame_lineRight_2.setMaximumSize(QtCore.QSize(500, 2))
        self.frame_lineRight_2.setStyleSheet("background-color: gray;")
        self.frame_lineRight_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lineRight_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lineRight_2.setObjectName("frame_lineRight_2")
        self.label_createAccount = QtWidgets.QLabel(self.frame_loginBox)
        self.label_createAccount.setGeometry(QtCore.QRect(147, 340, 115, 16))
        self.label_createAccount.setMaximumSize(QtCore.QSize(117, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.label_createAccount.setFont(font)
        self.label_createAccount.setStyleSheet("font-size: 12px;")
        self.label_createAccount.setObjectName("label_createAccount")
        self.frame_lineRight = QtWidgets.QFrame(self.frame_loginBox)
        self.frame_lineRight.setGeometry(QtCore.QRect(270, 350, 135, 2))
        self.frame_lineRight.setMaximumSize(QtCore.QSize(500, 2))
        self.frame_lineRight.setStyleSheet("background-color: gray;")
        self.frame_lineRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lineRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lineRight.setObjectName("frame_lineRight")
        self.frame = QtWidgets.QFrame(self.frame_loginBox)
        self.frame.setGeometry(QtCore.QRect(47, 65, 31, 31))
        self.frame.setStyleSheet("background: url(:/Icons/Assets/Icons/userIcon.png);\n"
"background-repeat: no-repeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame_loginBox)
        self.frame_2.setGeometry(QtCore.QRect(50, 165, 21, 31))
        self.frame_2.setStyleSheet("background: url(:/Icons/Assets/Icons/passwordIcon.png);\n"
"background-repeat: no-repeat;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_loginBox)
        self.verticalLayout.addWidget(self.frame_whiteRectangle)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.lineEdit_user.setPlaceholderText(_translate("Login", "Usuário"))
        self.lineEdit_password.setPlaceholderText(_translate("Login", "Senha"))
        self.pushButton_enter.setText(_translate("Login", "ENTRAR"))
        self.pushButton_createAccount.setText(_translate("Login", "CRIAR CONTA"))
        self.label_createAccount.setText(_translate("Login", "não tem uma conta?"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
