# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaListagemClientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaListagemClientes(object):
    def setupUi(self, TelaListagemClientes):
        TelaListagemClientes.setObjectName("TelaListagemClientes")
        TelaListagemClientes.resize(1280, 721)
        TelaListagemClientes.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(TelaListagemClientes)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_TopReqtangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_TopReqtangle.setMaximumSize(QtCore.QSize(16777215, 116))
        self.frame_TopReqtangle.setStyleSheet("background-color: #FFD580")
        self.frame_TopReqtangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopReqtangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopReqtangle.setObjectName("frame_TopReqtangle")
        self.pushButton_Sair = QtWidgets.QPushButton(self.frame_TopReqtangle)
        self.pushButton_Sair.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.pushButton_Sair.setStyleSheet("border-style: none;\n"
"font-size: 20px;\n"
"color: tomato;\n"
"background: #FFD580;\n"
"")
        self.pushButton_Sair.setObjectName("pushButton_Sair")
        self.verticalLayout.addWidget(self.frame_TopReqtangle)
        self.frame_DownReqtangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_DownReqtangle.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_DownReqtangle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_DownReqtangle.setStyleSheet("background-color: #faf9f6")
        self.frame_DownReqtangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DownReqtangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DownReqtangle.setObjectName("frame_DownReqtangle")
        self.label_NomeCliente = QtWidgets.QLabel(self.frame_DownReqtangle)
        self.label_NomeCliente.setGeometry(QtCore.QRect(80, 98, 131, 16))
        self.label_NomeCliente.setStyleSheet("font-size: 20px")
        self.label_NomeCliente.setObjectName("label_NomeCliente")
        self.frame_Divider = QtWidgets.QFrame(self.frame_DownReqtangle)
        self.frame_Divider.setGeometry(QtCore.QRect(0, 133, 1280, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Divider.sizePolicy().hasHeightForWidth())
        self.frame_Divider.setSizePolicy(sizePolicy)
        self.frame_Divider.setMinimumSize(QtCore.QSize(1280, 0))
        self.frame_Divider.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_Divider.setStyleSheet("border: 1px solid lightgray")
        self.frame_Divider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Divider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Divider.setObjectName("frame_Divider")
        self.label_EmailCliente = QtWidgets.QLabel(self.frame_DownReqtangle)
        self.label_EmailCliente.setGeometry(QtCore.QRect(400, 90, 181, 31))
        self.label_EmailCliente.setStyleSheet("font-size: 20px")
        self.label_EmailCliente.setObjectName("label_EmailCliente")
        self.label_TelefoneCliente = QtWidgets.QLabel(self.frame_DownReqtangle)
        self.label_TelefoneCliente.setGeometry(QtCore.QRect(750, 98, 161, 21))
        self.label_TelefoneCliente.setStyleSheet("font-size: 20px")
        self.label_TelefoneCliente.setObjectName("label_TelefoneCliente")
        self.pushButton_EditarCliente = QtWidgets.QPushButton(self.frame_DownReqtangle)
        self.pushButton_EditarCliente.setGeometry(QtCore.QRect(1080, 97, 75, 23))
        self.pushButton_EditarCliente.setStyleSheet("border-style: none;\n"
"font-size: 20px;\n"
"color: #FFAA00;\n"
"background: #FAF9F6;\n"
"")
        self.pushButton_EditarCliente.setObjectName("pushButton_EditarCliente")
        self.pushButton_DeletarCliente = QtWidgets.QPushButton(self.frame_DownReqtangle)
        self.pushButton_DeletarCliente.setGeometry(QtCore.QRect(1200, 95, 31, 31))
        self.pushButton_DeletarCliente.setToolTipDuration(-1)
        self.pushButton_DeletarCliente.setStyleSheet("color: #FFAA00;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"background-image: url(:/Icons/Assets/Icons/trashIcon.png);\n"
"")
        self.pushButton_DeletarCliente.setText("")
        self.pushButton_DeletarCliente.setObjectName("pushButton_DeletarCliente")
        self.verticalLayout.addWidget(self.frame_DownReqtangle)
        TelaListagemClientes.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaListagemClientes)
        QtCore.QMetaObject.connectSlotsByName(TelaListagemClientes)

    def retranslateUi(self, TelaListagemClientes):
        _translate = QtCore.QCoreApplication.translate
        TelaListagemClientes.setWindowTitle(_translate("TelaListagemClientes", "ListagemClientes"))
        self.pushButton_Sair.setText(_translate("TelaListagemClientes", "Sair"))
        self.label_NomeCliente.setText(_translate("TelaListagemClientes", "Nome Cliente"))
        self.label_EmailCliente.setText(_translate("TelaListagemClientes", "cliente@gmail.com"))
        self.label_TelefoneCliente.setText(_translate("TelaListagemClientes", "(67) 99323-5472"))
        self.pushButton_EditarCliente.setText(_translate("TelaListagemClientes", "Editar"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaListagemClientes = QtWidgets.QMainWindow()
    ui = Ui_TelaListagemClientes()
    ui.setupUi(TelaListagemClientes)
    TelaListagemClientes.show()
    sys.exit(app.exec_())
