# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaListagemClientes-Copy2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaListagemClientes(object):
    def setupUi(self, TelaListagemClientes):
        TelaListagemClientes.setObjectName("TelaListagemClientes")
        TelaListagemClientes.resize(1280, 720)
        TelaListagemClientes.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(TelaListagemClientes)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_TopReqtangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_TopReqtangle.setMinimumSize(QtCore.QSize(1280, 116))
        self.frame_TopReqtangle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_TopReqtangle.setStyleSheet("background-color: #FFD580")
        self.frame_TopReqtangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopReqtangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopReqtangle.setObjectName("frame_TopReqtangle")
        self.pushButton_Sair = QtWidgets.QPushButton(self.frame_TopReqtangle)
        self.pushButton_Sair.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.pushButton_Sair.setStyleSheet("border-style: none;\n"
"font-size: 20px;\n"
"color: tomato;\n"
"background: #FFD580;\n"
"")
        self.pushButton_Sair.setObjectName("pushButton_Sair")
        self.pushButton_Cadastrar = QtWidgets.QPushButton(self.frame_TopReqtangle)
        self.pushButton_Cadastrar.setGeometry(QtCore.QRect(810, 40, 141, 51))
        self.pushButton_Cadastrar.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-style: none;\n"
"border-radius: 5px;\n"
"font-size:20px;")
        self.pushButton_Cadastrar.setObjectName("pushButton_Cadastrar")
        self.pushButton_Alterar = QtWidgets.QPushButton(self.frame_TopReqtangle)
        self.pushButton_Alterar.setGeometry(QtCore.QRect(970, 40, 141, 51))
        self.pushButton_Alterar.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-style: none;\n"
"border-radius: 5px;\n"
"font-size:20px;")
        self.pushButton_Alterar.setObjectName("pushButton_Alterar")
        self.pushButton_Excluir = QtWidgets.QPushButton(self.frame_TopReqtangle)
        self.pushButton_Excluir.setGeometry(QtCore.QRect(1130, 40, 141, 51))
        self.pushButton_Excluir.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-style: none;\n"
"border-radius: 5px;\n"
"font-size:20px;")
        self.pushButton_Excluir.setObjectName("pushButton_Excluir")
        self.verticalLayout.addWidget(self.frame_TopReqtangle)
        self.frame_DownRectangle = QtWidgets.QFrame(self.centralwidget)
        self.frame_DownRectangle.setStyleSheet("background-color: rgb(255, 248, 233);")
        self.frame_DownRectangle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_DownRectangle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_DownRectangle.setObjectName("frame_DownRectangle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_DownRectangle)
        self.horizontalLayout.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_TabelaPessoas = QtWidgets.QTableWidget(self.frame_DownRectangle)
        self.tableWidget_TabelaPessoas.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_TabelaPessoas.setMaximumSize(QtCore.QSize(1065, 500))
        self.tableWidget_TabelaPessoas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_TabelaPessoas.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_TabelaPessoas.setStyleSheet("font-size: 18px;\n"
"border-style: none;\n"
"background: white;")
        self.tableWidget_TabelaPessoas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_TabelaPessoas.setLineWidth(1)
        self.tableWidget_TabelaPessoas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_TabelaPessoas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_TabelaPessoas.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_TabelaPessoas.setRowCount(1)
        self.tableWidget_TabelaPessoas.setObjectName("tableWidget_TabelaPessoas")
        self.tableWidget_TabelaPessoas.setColumnCount(3)
        self.tableWidget_TabelaPessoas.setColumnWidth(0, 375)
        self.tableWidget_TabelaPessoas.setColumnWidth(1, 435)
        self.tableWidget_TabelaPessoas.setColumnWidth(2, 225)
        self.loadDataTabela()


        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_TabelaPessoas.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_TabelaPessoas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_TabelaPessoas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_TabelaPessoas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout.addWidget(self.tableWidget_TabelaPessoas)
        self.verticalLayout.addWidget(self.frame_DownRectangle)
        TelaListagemClientes.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaListagemClientes)
        QtCore.QMetaObject.connectSlotsByName(TelaListagemClientes)

    def retranslateUi(self, TelaListagemClientes):
        _translate = QtCore.QCoreApplication.translate
        TelaListagemClientes.setWindowTitle(_translate("TelaListagemClientes", "ListagemClientes"))
        self.pushButton_Sair.setText(_translate("TelaListagemClientes", "Sair"))
        self.pushButton_Cadastrar.setText(_translate("TelaListagemClientes", "Cadastrar"))
        self.pushButton_Alterar.setText(_translate("TelaListagemClientes", "Alterar"))
        self.pushButton_Excluir.setText(_translate("TelaListagemClientes", "Deletar"))
        item = self.tableWidget_TabelaPessoas.verticalHeaderItem(0)
        item.setText(_translate("TelaListagemClientes", "1"))
        item = self.tableWidget_TabelaPessoas.horizontalHeaderItem(0)
        item.setText(_translate("TelaListagemClientes", "Nome"))
        item = self.tableWidget_TabelaPessoas.horizontalHeaderItem(1)
        item.setText(_translate("TelaListagemClientes", "E-Mail"))
        item = self.tableWidget_TabelaPessoas.horizontalHeaderItem(2)
        item.setText(_translate("TelaListagemClientes", "Telefone"))


    def loadDataTabela(self):
        pessoas = [
            {
                'nome': 'amongus',
                'telefone': '(67) 99323-5472',
                'email': 'amongus@gmail.com'
            },
            {
                'nome': 'paulo',
                'telefone': '(67) 99388-5452',
                'email': 'paulo@gmail.com'
            },
            {
                'nome': 'simone',
                'telefone': '(67) 98288-4455',
                'email': 'simone@gmail.com'
            },
            {
                'nome': 'rafael',
                'telefone': '(67) 91234-5678',
                'email': 'gabriel@gmail.com'
            },
            {
                'nome': 'amanda',
                'telefone': '(67) 98765-4321',
                'email': 'amanda@gmail.com'
            },
            {
                'nome': 'caio',
                'telefone': '(67) 99344-5444',
                'email': 'caio@gmail.com'
            },
            {
                'nome': 'rafael',
                'telefone': '(67) 91234-5678',
                'email': 'gabriel@gmail.com'
            },
            {
                'nome': 'amanda',
                'telefone': '(67) 98765-4321',
                'email': 'amanda@gmail.com'
            },
            {
                'nome': 'caio',
                'telefone': '(67) 99344-5444',
                'email': 'caio@gmail.com'
            },
            {
                'nome': 'rafael',
                'telefone': '(67) 91234-5678',
                'email': 'gabriel@gmail.com'
            },
            {
                'nome': 'amanda',
                'telefone': '(67) 98765-4321',
                'email': 'amanda@gmail.com'
            },
            {
                'nome': 'caio',
                'telefone': '(67) 99344-5444',
                'email': 'caio@gmail.com'
            },
        ]
        
        row = 0
        self.tableWidget_TabelaPessoas.setRowCount(len(pessoas))
        
        for pessoa in pessoas:
            self.tableWidget_TabelaPessoas.setRowHeight(row, 50)
            self.tableWidget_TabelaPessoas.setItem(row, 0, QtWidgets.QTableWidgetItem(pessoa['nome']))
            self.tableWidget_TabelaPessoas.setItem(row, 1, QtWidgets.QTableWidgetItem(pessoa['email']))
            self.tableWidget_TabelaPessoas.setItem(row, 2, QtWidgets.QTableWidgetItem(pessoa['telefone']))
            row = row + 1

import files_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaListagemClientes = QtWidgets.QMainWindow()
    ui = Ui_TelaListagemClientes()
    ui.setupUi(TelaListagemClientes)
    TelaListagemClientes.show()
    sys.exit(app.exec_())
